config/routes.rb
Rails.application.routes.draw do
  resources :livros
  devise_for :users, :controllers => { registrations:'registrationscontroller' }
  get 'home/index'
  root 'livros#index'
  resources :'help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/livro.rb
class Livro < ApplicationRecord
belongs_to :user
  has_attached_file :imagem, styles: { medium: "300x300>", thumb: "100x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :livro
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/help_controller.rb
class HelpController < ApplicationController

def index
render = 'index'
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_livro, only: [:show, :edit, :update, :destroy]
  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end
  # GET /livros/new
  def new
    @livro = current_user.livro.build
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = current_user.livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :edicao, :ano, :descricao, :imagem, :user_id)
    end
end

app/controllers/registrationscontroller_controller.rb
class RegistrationscontrollerController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:phone, :address, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:phone, :address, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/registrationscontroller_helper.rb
module RegistrationscontrollerHelper
end

app/views/help/index.html.erb
<h2>Biblioteca Virtual About</h2>
<div class="field">
<p>
	A Biblioteca virtual não se responsabiliza pelas transações realizadas no site. O site tem apenas o objetivo de compartilhar sobre os livros de interesses comuns entre os clientes. Tendo consiência disso não serão levados em conta reclamações a respeito das transações sendo que estás estão apenas a pá apenas do interessado em trocar ou comprar o livro.
</p>

</div>
 

</ul>

app/views/home/index.html.erb
<h2>Biblioteca Virtual</h2>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca Virtual</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "Main">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container_menu_top">
        <nav>
          <%= image_tag "pilha-de-livros-de-tres_318-45543.png" %>
          <%= link_to "Biblioteca Virtual ", '/', id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
            <li><button type="button" class="btn btn-primary"><%= link_to "Home",   '/' %></button></li>
            <li><button type="button" class="btn btn-primary"><%= link_to "Help",   '/help' %></button></li>
            <% if user_signed_in? %>
            <li><button type="button" class="btn btn-primary"><%= link_to "Log out",destroy_user_session_path, :method=>'delete'%></button></li>
            <li><button type="button" class="btn btn-primary"><%= link_to "New Book", new_livro_path%></button></li>
            <%else%>
            <li><button type="button" class="btn btn-primary"><%= link_to "Log in", '/users/sign_in' %></button></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_for @livro, html: { multipart: true } do |form| %>
  <% if livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :livro_titulo %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor, id: :livro_autor %>
  </div>

  <div class="field">
    <%= form.label :edicao %>
    <%= form.number_field :edicao, id: :livro_edicao %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :livro_ano %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :livro_descricao %>
  </div>
  
  <div class="field">
    <%= form.label :imagem %><br />
    <%= form.file_field :imagem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h2>Editing Livro</h2>
<div class = "link">
  <%= render 'form', livro: @livro %>
    <%= link_to 'Show', @livro %> |
    <%= link_to 'Back', livros_path %> |
    <%= link_to 'Edit', edit_livro_path(@livro) %> |
    <%= link_to "Delete", livro_path(@livro), :confirm => "Are you sure?", :method => :delete %>
  </div>

app/views/livros/index.html.erb
<h2>Livros</h2>
<body class = "livros_body">
    <% @livros.each do |livro| %>
<div class="container-1">
<div class="row">
  <div class="col">
    <div class="thumbnail">
      <img <%= image_tag(livro.imagem.url(:medium)) %>
      <div class="caption">
        <h3>Titulo: <%=livro.titulo %></h3>
            <p>Autor: <%= livro.autor %></p>
            <p>Edição: <%= livro.edicao %></p>
            <p>Ano: <%= livro.ano %></p>
        <p>
        <% if user_signed_in? %>
        <button type="button" class="btn btn-primary"><%= link_to 'Read More', livro %></button></td>
        <%else%>
        <button type="button" class="btn btn-primary"><%= link_to 'Read More', '/users/sign_in' %></button></td>
        <% end %>
        </p>
      </div>
    </div>
  </div>
</div>
</div>
  <% end %>

</body>

app/views/livros/new.html.erb
<h2>New Livro</h2>

<div class="editing">
<%= render 'form', livro: @livro %>
</div>
<div class="link">
<%= link_to 'Back', livros_path %>
</div>

app/views/livros/show.html.erb
<p id="notice"><strong>Noticia: <%= notice %></strong></p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Edição:</strong>
  <%= @livro.edicao %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @livro.ano %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @livro.descricao %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= image_tag @livro.imagem(:medium) if @livro.imagem.present? %>
</p>
<div class = 'link'>

  <% if user_signed_in? %>
  <%= link_to 'Back', livros_path %> |
  <%= link_to 'Edit', edit_livro_path(@livro) %> |
  <%else%>
  <%= link_to 'Back', livros_path %> |
  <% end %>

</div>